#cloud-config

runcmd:
    - sudo apt install python-minimal
    - sudo apt-add-repository -y ppa:ansible/ansible
    - sudo apt-get -y update
    - sudo apt-get -y upgrade
    - sudo apt-get install -y ansible
    - sudo apt-get install -y --force-yes git &&\
      sudo apt-get clean
    - cd /home/ubuntu
    - sudo git clone https://github.com/QTLaaS/QTLaaS.git
    - ansible-playbook -b /home/ubuntu/QTLaaS/spark_deployment.yml
